apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation

on:
  push:
    branches:
      - '**'

jobs:
  ci-job:
    steps:
      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - name: Build Go App
        uses: docker://golang:1.20
        run: |
          go build -v ./...
      - name: Run tests
        uses: docker://golang:1.20
        run: |
          go test -v ./...
      - name: Docker sign-in
        id: docker-sign-in-id
        uses: docker://alpine:3.17
        env:
          DOCKER_USERNAME: ${{ vars.QUICKSTART_DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.QUICKSTART_DOCKER_PASSWORD }}
        run: |
          AUTH=$(echo -n "${DOCKER_USERNAME}:${DOCKER_PASSWORD}" | base64)
          mkdir -p $HOME/.docker
          cat << EOF > "$HOME/.docker/config.json"
          {
              "auths": {
                "https://index.docker.io/v1/": {
                    "auth": "${AUTH}"
                }
              }
          }
          EOF
      - name: Push image to registry
        uses: cloudbees-io/kaniko@v1
        with:
          destination: index.docker.io/${{ vars.QUICKSTART_DOCKER_USERNAME }}/my-sample-go-app:1.0.0